// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Slice for *rss-entries → Slice zone*
 */
export type RssEntriesDocumentDataBodyRssFeedSlice = prismic.Slice<
  "rss_feed",
  Record<string, never>,
  never
>;

type RssEntriesDocumentDataBodySlice = RssEntriesDocumentDataBodyRssFeedSlice;

/**
 * Content for rss-entries documents
 */
interface RssEntriesDocumentData {
  /**
   * Slice zone field in *rss-entries*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: rss-entries.body[]
   * - **Tab**: feeds
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<RssEntriesDocumentDataBodySlice>;
}

/**
 * rss-entries document from Prismic
 *
 * - **API ID**: `rss-entries`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RssEntriesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RssEntriesDocumentData>,
    "rss-entries",
    Lang
  >;

type RssSinglePageDocumentDataSlicesSlice = RssContainerSlice;

/**
 * Content for RSS Single Page documents
 */
interface RssSinglePageDocumentData {
  /**
   * Slice Zone field in *RSS Single Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: rss_single_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<RssSinglePageDocumentDataSlicesSlice> /**
   * Meta Description field in *RSS Single Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: rss_single_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *RSS Single Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rss_single_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *RSS Single Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: rss_single_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * RSS Single Page document from Prismic
 *
 * - **API ID**: `rss_single_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RssSinglePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RssSinglePageDocumentData>,
    "rss_single_page",
    Lang
  >;

export type AllDocumentTypes = RssEntriesDocument | RssSinglePageDocument;

/**
 * Default variation for RssContainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RssContainerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *RssContainer*
 */
type RssContainerSliceVariation = RssContainerSliceDefault;

/**
 * RssContainer Shared Slice
 *
 * - **API ID**: `rss_container`
 * - **Description**: RssContainer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RssContainerSlice = prismic.SharedSlice<
  "rss_container",
  RssContainerSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      RssEntriesDocument,
      RssEntriesDocumentData,
      RssEntriesDocumentDataBodySlice,
      RssSinglePageDocument,
      RssSinglePageDocumentData,
      RssSinglePageDocumentDataSlicesSlice,
      AllDocumentTypes,
      RssContainerSlice,
      RssContainerSliceVariation,
      RssContainerSliceDefault,
    };
  }
}
